### ISSUE TITLE
Could not find method ppkDependencyGraphPluginExtension() for arguments

### ISSUE THREAD

**Issue by kawpii** [acterics/apk-dependency-graph-gradle-plugin#4]
`Could not find method ppkDependencyGraphPluginExtension() for arguments `

tried following `apkDependencyGraphPluginExtension` since most probably above one is typo in the readme, but same result

`Could not find method apkDependencyGraphPluginExtension() for arguments`

**Comment by acterics** [comment]
Thank you for issue. Project readme is out of date. Try 
`apkDependencyGraph` in your build script, it should work correctly.
